### ISSUE TITLE
RuntimeError: can't register atexit after shutdown

### ISSUE THREAD

**Issue by MeiAxillson** [LyubomirT/mass-discord-moderation#6]
**Description the bug:**
This repo was cloned to Replit, when I Run — after few minutes Im got the RuntimeError.

**To Reproduce**
Steps to reproduce the behavior on the video on Discord: (bc this video is big for 2 minutes)

https://media.discordapp.net/attachments/970370306403356753/1218125102814724096/RPReplay_Final1710493886.mov?ex=66068668&is=65f41168&hm=fb4cc484cbd78ce09acb0a42b0b894ddcf1aee0ecd9ba1d3a13e8b40c1b74694&

**Expected behavior**

**Screenshots**
![Uploading 0DABAEA6-9357-4651-9614-134A7CA7A47A.png…]()
If this screen isn’t available — check this on Discord too: https://media.discordapp.net/attachments/970370306403356753/1218125451709517844/IMG_0131.png?ex=660686bb&is=65f411bb&hm=bc9835f6f8073f134163859d7f2ccb9de9d0185c5e23b9dc28bd89e43110761a&

**Smartphone:**
 - Device: [iPad Pro 11-inch]
 - OS: [iOS 16.3]
 - Workplace: Replit

**Comment by LyubomirT** [comment]
Resolved in the Discord server.
